# Generated by Django 4.2 on 2025-11-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('VENDA', 'Venda'), ('AJUSTE_SAIDA', 'Ajuste (Saída)'), ('AJUSTE_ENTRADA', 'Ajuste (Entrada)'), ('DEVOLUCAO', 'Devolução')], max_length=20, verbose_name='Tipo de Movimento'),
        ),
    ]
