# Generated by Django 4.2 on 2025-10-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_variation',
            field=models.BooleanField(default=False, verbose_name='Possui Variação'),
        ),
    ]
