# Generated by Django 4.2 on 2025-10-11 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_alter_category_options_alter_color_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE_SAIDA', 'Ajuste (Saída)'), ('AJUSTE_ENTRADA', 'Ajuste (Entrada)'), ('DEVOLUCAO', 'Devolução')], max_length=20, verbose_name='Tipo de Movimento')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Unitário')),
                ('movement_date', models.DateTimeField(auto_now_add=True, verbose_name='Data do Movimento')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='product.productvariation', verbose_name='Variação de Produto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Movimento de Estoque',
                'verbose_name_plural': 'Movimentos de Estoque',
                'ordering': ['-movement_date'],
            },
        ),
    ]
