# Generated by Django 4.2 on 2026-06-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_cost_price'),
        ('product', '0002_product_cover_image_productimage'),
    ]

    operations = [
    ]
