--
-- PostgreSQL database dump
--

-- Dumped from database version 15.17
-- Dumped by pg_dump version 17.0

-- Started on 2026-03-23 14:31:54

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 221 (class 1259 OID 16412)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: gesthar_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO gesthar_user;

--
-- TOC entry 220 (class 1259 OID 16411)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: gesthar_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16420)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: gesthar_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO gesthar_user;

--
-- TOC entry 222 (class 1259 OID 16419)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: gesthar_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16406)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: gesthar_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO gesthar_user;

--
-- TOC entry 218 (class 1259 OID 16405)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: gesthar_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 16539)
-- Name: customer_address; Type: TABLE; Schema: public; Owner: gesthar_user
--

CREATE TABLE public.customer_address (
    id bigint NOT NULL,
    cep character varying(10) NOT NULL,
    state character varying(100) NOT NULL,
    city character varying(100) NOT NULL,
    neighborhood character varying(100) NOT NULL,
    street character varying(255) NOT NULL,
    number character varying(20) NOT NULL,
    complement character varying(255),
    customer_id bigint NOT NULL
);


ALTER TABLE public.customer_address OWNER TO gesthar_user;

--
-- TOC entry 234 (class 1259 OID 16538)
-- Name: customer_address_id_seq; Type: SEQUENCE; Schema: public; Owner: gesthar_user
--

ALTER TABLE public.customer_address ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 16527)
-- Name: customer_customer; Type: TABLE; Schema: public; Owner: gesthar_user
--

CREATE TABLE public.customer_customer (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    cpf_cnpj character varying(18) NOT NULL,
    birth_date date,
    email character varying(254) NOT NULL,
    phone character varying(20),
    baby_due_date date,
    note text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    size_preferences character varying(100)
);


ALTER TABLE public.customer_customer OWNER TO gesthar_user;

--
-- TOC entry 232 (class 1259 OID 16526)
-- Name: customer_customer_id_seq; Type: SEQUENCE; Schema: public; Owner: gesthar_user
--

ALTER TABLE public.customer_customer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16506)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: gesthar_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO gesthar_user;

--
-- TOC entry 230 (class 1259 OID 16505)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: gesthar_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16398)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: gesthar_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO gesthar_user;

--
-- TOC entry 216 (class 1259 OID 16397)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: gesthar_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 16390)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: gesthar_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO gesthar_user;

--
-- TOC entry 214 (class 1259 OID 16389)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: gesthar_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 258 (class 1259 OID 16737)
-- Name: django_session; Type: TABLE; Schema: public; Owner: gesthar_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO gesthar_user;

--
-- TOC entry 237 (class 1259 OID 16558)
-- Name: product_category; Type: TABLE; Schema: public; Owner: gesthar_user
--

CREATE TABLE public.product_category (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    is_active boolean NOT NULL
);


ALTER TABLE public.product_category OWNER TO gesthar_user;

--
-- TOC entry 236 (class 1259 OID 16557)
-- Name: product_category_id_seq; Type: SEQUENCE; Schema: public; Owner: gesthar_user
--

ALTER TABLE public.product_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 16568)
-- Name: product_color; Type: TABLE; Schema: public; Owner: gesthar_user
--

CREATE TABLE public.product_color (
    id bigint NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.product_color OWNER TO gesthar_user;

--
-- TOC entry 238 (class 1259 OID 16567)
-- Name: product_color_id_seq; Type: SEQUENCE; Schema: public; Owner: gesthar_user
--

ALTER TABLE public.product_color ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_color_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 16576)
-- Name: product_product; Type: TABLE; Schema: public; Owner: gesthar_user
--

CREATE TABLE public.product_product (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    selling_price numeric(10,2) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    category_id bigint NOT NULL
);


ALTER TABLE public.product_product OWNER TO gesthar_user;

--
-- TOC entry 240 (class 1259 OID 16575)
-- Name: product_product_id_seq; Type: SEQUENCE; Schema: public; Owner: gesthar_user
--

ALTER TABLE public.product_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 249 (class 1259 OID 16612)
-- Name: product_productsupplier; Type: TABLE; Schema: public; Owner: gesthar_user
--

CREATE TABLE public.product_productsupplier (
    id bigint NOT NULL,
    cost_price numeric(10,2) NOT NULL,
    added_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL,
    supplier_id bigint NOT NULL
);


ALTER TABLE public.product_productsupplier OWNER TO gesthar_user;

--
-- TOC entry 248 (class 1259 OID 16611)
-- Name: product_productsupplier_id_seq; Type: SEQUENCE; Schema: public; Owner: gesthar_user
--

ALTER TABLE public.product_productsupplier ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_productsupplier_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 16602)
-- Name: product_productvariation; Type: TABLE; Schema: public; Owner: gesthar_user
--

CREATE TABLE public.product_productvariation (
    id bigint NOT NULL,
    sku character varying(50) NOT NULL,
    stock bigint NOT NULL,
    minimum_stock bigint NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    color_id bigint NOT NULL,
    product_id bigint NOT NULL,
    size_id bigint NOT NULL,
    CONSTRAINT product_productvariation_minimum_stock_check CHECK ((minimum_stock >= 0)),
    CONSTRAINT product_productvariation_stock_check CHECK ((stock >= 0)),
    CONSTRAINT stock_non_negative CHECK (((stock >= 0) AND (minimum_stock >= 0)))
);


ALTER TABLE public.product_productvariation OWNER TO gesthar_user;

--
-- TOC entry 246 (class 1259 OID 16601)
-- Name: product_productvariation_id_seq; Type: SEQUENCE; Schema: public; Owner: gesthar_user
--

ALTER TABLE public.product_productvariation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_productvariation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 16586)
-- Name: product_size; Type: TABLE; Schema: public; Owner: gesthar_user
--

CREATE TABLE public.product_size (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    is_active boolean NOT NULL
);


ALTER TABLE public.product_size OWNER TO gesthar_user;

--
-- TOC entry 242 (class 1259 OID 16585)
-- Name: product_size_id_seq; Type: SEQUENCE; Schema: public; Owner: gesthar_user
--

ALTER TABLE public.product_size ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_size_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 16594)
-- Name: product_supplier; Type: TABLE; Schema: public; Owner: gesthar_user
--

CREATE TABLE public.product_supplier (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    is_active boolean NOT NULL
);


ALTER TABLE public.product_supplier OWNER TO gesthar_user;

--
-- TOC entry 244 (class 1259 OID 16593)
-- Name: product_supplier_id_seq; Type: SEQUENCE; Schema: public; Owner: gesthar_user
--

ALTER TABLE public.product_supplier ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_supplier_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 251 (class 1259 OID 16669)
-- Name: sales_cashregister; Type: TABLE; Schema: public; Owner: gesthar_user
--

CREATE TABLE public.sales_cashregister (
    id bigint NOT NULL,
    is_active boolean NOT NULL,
    deleted_at timestamp with time zone,
    opening_balance numeric(12,2) NOT NULL,
    closing_balance numeric(12,2),
    opened_at timestamp with time zone NOT NULL,
    closed_at timestamp with time zone,
    status character varying(10) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.sales_cashregister OWNER TO gesthar_user;

--
-- TOC entry 250 (class 1259 OID 16668)
-- Name: sales_cashregister_id_seq; Type: SEQUENCE; Schema: public; Owner: gesthar_user
--

ALTER TABLE public.sales_cashregister ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_cashregister_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 253 (class 1259 OID 16675)
-- Name: sales_sale; Type: TABLE; Schema: public; Owner: gesthar_user
--

CREATE TABLE public.sales_sale (
    id bigint NOT NULL,
    is_active boolean NOT NULL,
    deleted_at timestamp with time zone,
    change_amount numeric(12,2) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone,
    status character varying(20) NOT NULL,
    gross_amount numeric(12,2) NOT NULL,
    discount_amount numeric(12,2) NOT NULL,
    net_amount numeric(12,2) NOT NULL,
    cash_register_session_id bigint,
    customer_id bigint,
    user_id bigint NOT NULL
);


ALTER TABLE public.sales_sale OWNER TO gesthar_user;

--
-- TOC entry 252 (class 1259 OID 16674)
-- Name: sales_sale_id_seq; Type: SEQUENCE; Schema: public; Owner: gesthar_user
--

ALTER TABLE public.sales_sale ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_sale_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 257 (class 1259 OID 16687)
-- Name: sales_saleitem; Type: TABLE; Schema: public; Owner: gesthar_user
--

CREATE TABLE public.sales_saleitem (
    id bigint NOT NULL,
    product_sku_snapshot character varying(50) NOT NULL,
    product_name_snapshot character varying(255) NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    discount numeric(10,2) NOT NULL,
    total_price numeric(12,2) NOT NULL,
    sale_id bigint NOT NULL,
    variation_id bigint NOT NULL,
    CONSTRAINT sales_saleitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.sales_saleitem OWNER TO gesthar_user;

--
-- TOC entry 256 (class 1259 OID 16686)
-- Name: sales_saleitem_id_seq; Type: SEQUENCE; Schema: public; Owner: gesthar_user
--

ALTER TABLE public.sales_saleitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_saleitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 255 (class 1259 OID 16681)
-- Name: sales_salepayment; Type: TABLE; Schema: public; Owner: gesthar_user
--

CREATE TABLE public.sales_salepayment (
    id bigint NOT NULL,
    method character varying(20) NOT NULL,
    amount numeric(12,2) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    sale_id bigint NOT NULL
);


ALTER TABLE public.sales_salepayment OWNER TO gesthar_user;

--
-- TOC entry 254 (class 1259 OID 16680)
-- Name: sales_salepayment_id_seq; Type: SEQUENCE; Schema: public; Owner: gesthar_user
--

ALTER TABLE public.sales_salepayment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_salepayment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 260 (class 1259 OID 16747)
-- Name: stock_stockmovement; Type: TABLE; Schema: public; Owner: gesthar_user
--

CREATE TABLE public.stock_stockmovement (
    id bigint NOT NULL,
    movement_type character varying(20) NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(10,2),
    movement_date timestamp with time zone NOT NULL,
    notes text,
    product_variation_id bigint NOT NULL,
    supplier_id bigint,
    user_id bigint NOT NULL,
    CONSTRAINT stock_stockmovement_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.stock_stockmovement OWNER TO gesthar_user;

--
-- TOC entry 259 (class 1259 OID 16746)
-- Name: stock_stockmovement_id_seq; Type: SEQUENCE; Schema: public; Owner: gesthar_user
--

ALTER TABLE public.stock_stockmovement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_stockmovement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16452)
-- Name: user_usergesthar; Type: TABLE; Schema: public; Owner: gesthar_user
--

CREATE TABLE public.user_usergesthar (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    username character varying(150),
    cpf character varying(14) NOT NULL,
    email character varying(254) NOT NULL,
    phone_number character varying(15),
    hire_date date,
    birth_date date,
    exit_date date,
    notes text,
    role character varying(100)
);


ALTER TABLE public.user_usergesthar OWNER TO gesthar_user;

--
-- TOC entry 227 (class 1259 OID 16464)
-- Name: user_usergesthar_groups; Type: TABLE; Schema: public; Owner: gesthar_user
--

CREATE TABLE public.user_usergesthar_groups (
    id bigint NOT NULL,
    usergesthar_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.user_usergesthar_groups OWNER TO gesthar_user;

--
-- TOC entry 226 (class 1259 OID 16463)
-- Name: user_usergesthar_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: gesthar_user
--

ALTER TABLE public.user_usergesthar_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_usergesthar_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16451)
-- Name: user_usergesthar_id_seq; Type: SEQUENCE; Schema: public; Owner: gesthar_user
--

ALTER TABLE public.user_usergesthar ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_usergesthar_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16470)
-- Name: user_usergesthar_user_permissions; Type: TABLE; Schema: public; Owner: gesthar_user
--

CREATE TABLE public.user_usergesthar_user_permissions (
    id bigint NOT NULL,
    usergesthar_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.user_usergesthar_user_permissions OWNER TO gesthar_user;

--
-- TOC entry 228 (class 1259 OID 16469)
-- Name: user_usergesthar_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: gesthar_user
--

ALTER TABLE public.user_usergesthar_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_usergesthar_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3680 (class 0 OID 16412)
-- Dependencies: 221
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: gesthar_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- TOC entry 3682 (class 0 OID 16420)
-- Dependencies: 223
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: gesthar_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- TOC entry 3678 (class 0 OID 16406)
-- Dependencies: 219
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: gesthar_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add Categoria	6	add_category
22	Can change Categoria	6	change_category
23	Can delete Categoria	6	delete_category
24	Can view Categoria	6	view_category
25	Can add Cor	7	add_color
26	Can change Cor	7	change_color
27	Can delete Cor	7	delete_color
28	Can view Cor	7	view_color
29	Can add Produto	8	add_product
30	Can change Produto	8	change_product
31	Can delete Produto	8	delete_product
32	Can view Produto	8	view_product
33	Can add Tamanho	9	add_size
34	Can change Tamanho	9	change_size
35	Can delete Tamanho	9	delete_size
36	Can view Tamanho	9	view_size
37	Can add Fornecedor	10	add_supplier
38	Can change Fornecedor	10	change_supplier
39	Can delete Fornecedor	10	delete_supplier
40	Can view Fornecedor	10	view_supplier
41	Can add Variação de Produto	11	add_productvariation
42	Can change Variação de Produto	11	change_productvariation
43	Can delete Variação de Produto	11	delete_productvariation
44	Can view Variação de Produto	11	view_productvariation
45	Can add Fornecedor do Produto	12	add_productsupplier
46	Can change Fornecedor do Produto	12	change_productsupplier
47	Can delete Fornecedor do Produto	12	delete_productsupplier
48	Can view Fornecedor do Produto	12	view_productsupplier
49	Can add Cliente	13	add_customer
50	Can change Cliente	13	change_customer
51	Can delete Cliente	13	delete_customer
52	Can view Cliente	13	view_customer
53	Can add Endereço	14	add_address
54	Can change Endereço	14	change_address
55	Can delete Endereço	14	delete_address
56	Can view Endereço	14	view_address
57	Can add Usuário	15	add_usergesthar
58	Can change Usuário	15	change_usergesthar
59	Can delete Usuário	15	delete_usergesthar
60	Can view Usuário	15	view_usergesthar
61	Can add Movimento de Estoque	16	add_stockmovement
62	Can change Movimento de Estoque	16	change_stockmovement
63	Can delete Movimento de Estoque	16	delete_stockmovement
64	Can view Movimento de Estoque	16	view_stockmovement
65	Can add Sessão de Caixa	17	add_cashregister
66	Can change Sessão de Caixa	17	change_cashregister
67	Can delete Sessão de Caixa	17	delete_cashregister
68	Can view Sessão de Caixa	17	view_cashregister
69	Can add Venda	18	add_sale
70	Can change Venda	18	change_sale
71	Can delete Venda	18	delete_sale
72	Can view Venda	18	view_sale
73	Can add Pagamento	19	add_salepayment
74	Can change Pagamento	19	change_salepayment
75	Can delete Pagamento	19	delete_salepayment
76	Can view Pagamento	19	view_salepayment
77	Can add Item da Venda	20	add_saleitem
78	Can change Item da Venda	20	change_saleitem
79	Can delete Item da Venda	20	delete_saleitem
80	Can view Item da Venda	20	view_saleitem
\.


--
-- TOC entry 3694 (class 0 OID 16539)
-- Dependencies: 235
-- Data for Name: customer_address; Type: TABLE DATA; Schema: public; Owner: gesthar_user
--

COPY public.customer_address (id, cep, state, city, neighborhood, street, number, complement, customer_id) FROM stdin;
\.


--
-- TOC entry 3692 (class 0 OID 16527)
-- Dependencies: 233
-- Data for Name: customer_customer; Type: TABLE DATA; Schema: public; Owner: gesthar_user
--

COPY public.customer_customer (id, name, cpf_cnpj, birth_date, email, phone, baby_due_date, note, created_at, updated_at, size_preferences) FROM stdin;
\.


--
-- TOC entry 3690 (class 0 OID 16506)
-- Dependencies: 231
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: gesthar_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- TOC entry 3676 (class 0 OID 16398)
-- Dependencies: 217
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: gesthar_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	product	category
7	product	color
8	product	product
9	product	size
10	product	supplier
11	product	productvariation
12	product	productsupplier
13	customer	customer
14	customer	address
15	user	usergesthar
16	stock	stockmovement
17	sales	cashregister
18	sales	sale
19	sales	salepayment
20	sales	saleitem
\.


--
-- TOC entry 3674 (class 0 OID 16390)
-- Dependencies: 215
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: gesthar_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-01-13 19:47:34.560721+00
2	contenttypes	0002_remove_content_type_name	2026-01-13 19:47:34.572707+00
3	auth	0001_initial	2026-01-13 19:47:34.696524+00
4	auth	0002_alter_permission_name_max_length	2026-01-13 19:47:34.706768+00
5	auth	0003_alter_user_email_max_length	2026-01-13 19:47:34.717883+00
6	auth	0004_alter_user_username_opts	2026-01-13 19:47:34.725901+00
7	auth	0005_alter_user_last_login_null	2026-01-13 19:47:34.733487+00
8	auth	0006_require_contenttypes_0002	2026-01-13 19:47:34.739569+00
9	auth	0007_alter_validators_add_error_messages	2026-01-13 19:47:34.747026+00
10	auth	0008_alter_user_username_max_length	2026-01-13 19:47:34.759181+00
11	auth	0009_alter_user_last_name_max_length	2026-01-13 19:47:34.769414+00
12	auth	0010_alter_group_name_max_length	2026-01-13 19:47:34.777513+00
13	auth	0011_update_proxy_permissions	2026-01-13 19:47:34.78753+00
14	auth	0012_alter_user_first_name_max_length	2026-01-13 19:47:34.794424+00
15	user	0001_initial	2026-01-13 19:47:34.902816+00
16	admin	0001_initial	2026-01-13 19:47:34.945355+00
17	admin	0002_logentry_remove_auto_add	2026-01-13 19:47:34.953327+00
18	admin	0003_logentry_add_action_flag_choices	2026-01-13 19:47:34.962667+00
19	customer	0001_initial	2026-01-13 19:47:35.031594+00
20	customer	0002_update_customer_fields	2026-01-13 19:47:35.06649+00
21	product	0001_initial	2026-01-13 19:47:35.298988+00
22	product	0002_remove_size_code_alter_size_name	2026-01-13 19:47:35.322447+00
23	sales	0001_initial	2026-01-13 19:50:17.340757+00
24	sessions	0001_initial	2026-01-13 19:50:17.373321+00
25	stock	0001_initial	2026-01-13 19:50:17.426007+00
26	user	0002_alter_usergesthar_cpf	2026-01-13 19:50:17.440914+00
27	user	0003_usergesthar_birth_date_usergesthar_exit_date_and_more	2026-01-13 19:50:17.475498+00
\.


--
-- TOC entry 3717 (class 0 OID 16737)
-- Dependencies: 258
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: gesthar_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
3548861rwoc7gx44z8ab5hh98h2daszq	.eJxVjMEOwiAQRP-FsyFuoVQ8evcbyO7CStVAUtqT8d-VpAe9Tea9mZcKuK05bC0tYY7qrEAdfjtCfqTSQbxjuVXNtazLTLoreqdNX2tMz8vu_h1kbPm7HkHsaJAdi_PgiXoaIog3YI8mDd4xRfEC0QjyRGkyJzFECawwoXp_AP_DOVE:1vfkUi:FU2CB3lqbkxWxkC_ZiY9TRzenMW-oDwGXwMlJqkVuao	2026-01-27 19:56:00.915915+00
6bm3v83n9swjrrk5vpof7jf2x28jul2w	.eJxVjMsOwiAQAP-FsyHl5S4evfsNZGFBqoYmpT0Z_92Q9KDXmcm8RaB9q2HveQ0zi4vQ4vTLIqVnbkPwg9p9kWlp2zpHORJ52C5vC-fX9Wj_BpV6HVsLxmQgtEVZ9AYBIxtwZ5eit1ohW_CoAYqLadKleOOSZTMV8gykxOcLsn03Bw:1w4j2T:igwyP0uuE0GFVBG_GJA8knuSga299xEdE0vppsRyiDw	2026-04-06 17:26:05.524053+00
\.


--
-- TOC entry 3696 (class 0 OID 16558)
-- Dependencies: 237
-- Data for Name: product_category; Type: TABLE DATA; Schema: public; Owner: gesthar_user
--

COPY public.product_category (id, name, description, is_active) FROM stdin;
4	Moda Gestante	Roupas casuais e sociais para gestantes	t
5	Lingerie Maternidade	Sutiãs, calcinhas e cintas	t
6	Pijamas e Camisolas	Linha noite para gestante e amamentação	t
\.


--
-- TOC entry 3698 (class 0 OID 16568)
-- Dependencies: 239
-- Data for Name: product_color; Type: TABLE DATA; Schema: public; Owner: gesthar_user
--

COPY public.product_color (id, name) FROM stdin;
11	Preto
12	Branco
13	Bege
14	Rosa Bebê
15	Azul Marinho
16	Cinza Mescla
17	Vinho
18	Verde Militar
19	Estampado Floral
20	Listrado
21	N/A
\.


--
-- TOC entry 3700 (class 0 OID 16576)
-- Dependencies: 241
-- Data for Name: product_product; Type: TABLE DATA; Schema: public; Owner: gesthar_user
--

COPY public.product_product (id, name, description, selling_price, is_active, created_at, updated_at, category_id) FROM stdin;
15	Vestido Midi Canelado	Produto oficial da coleção Moda Gestante.	89.90	t	2026-01-13 19:54:29.971533+00	2026-01-13 19:54:29.971545+00	4
16	Calça Jeans Cós Elástico	Produto oficial da coleção Moda Gestante.	129.90	t	2026-01-13 19:54:29.986158+00	2026-01-13 19:54:29.986163+00	4
17	Bata Soltinha Viscose	Produto oficial da coleção Moda Gestante.	79.90	t	2026-01-13 19:54:29.993898+00	2026-01-13 19:54:29.993903+00	4
18	Shorts Gestante Linho	Produto oficial da coleção Moda Gestante.	89.90	t	2026-01-13 19:54:30.002347+00	2026-01-13 19:54:30.002354+00	4
19	Legging Gestante Básica	Produto oficial da coleção Moda Gestante.	59.90	t	2026-01-13 19:54:30.014395+00	2026-01-13 19:54:30.014401+00	4
20	Macacão Longo Malha	Produto oficial da coleção Moda Gestante.	119.90	t	2026-01-13 19:54:30.02594+00	2026-01-13 19:54:30.025945+00	4
21	Blusa Amamentação Transpassada	Produto oficial da coleção Moda Gestante.	69.90	t	2026-01-13 19:54:30.032119+00	2026-01-13 19:54:30.032124+00	4
22	Vestido Longo Estampado	Produto oficial da coleção Moda Gestante.	149.90	t	2026-01-13 19:54:30.040453+00	2026-01-13 19:54:30.040458+00	4
23	Saia Midi Malha	Produto oficial da coleção Moda Gestante.	79.90	t	2026-01-13 19:54:30.044007+00	2026-01-13 19:54:30.044014+00	4
24	Regata Básica Gestante	Produto oficial da coleção Moda Gestante.	39.90	t	2026-01-13 19:54:30.048646+00	2026-01-13 19:54:30.048652+00	4
25	Cardigan Alongado Tricô	Produto oficial da coleção Moda Gestante.	99.90	t	2026-01-13 19:54:30.056247+00	2026-01-13 19:54:30.056253+00	4
26	Vestido Festa Gestante Renda	Produto oficial da coleção Moda Gestante.	199.90	t	2026-01-13 19:54:30.063326+00	2026-01-13 19:54:30.063332+00	4
27	Jardineira Jeans Gestante	Produto oficial da coleção Moda Gestante.	159.90	t	2026-01-13 19:54:30.069649+00	2026-01-13 19:54:30.069654+00	4
28	Sutiã Amamentação Renda	Produto oficial da coleção Lingerie Maternidade.	59.90	t	2026-01-13 19:54:30.074687+00	2026-01-13 19:54:30.074695+00	5
29	Cinta Pós-Parto Modeladora	Produto oficial da coleção Lingerie Maternidade.	89.90	t	2026-01-13 19:54:30.083565+00	2026-01-13 19:54:30.08357+00	5
30	Calcinha Pós-Parto Conforto	Produto oficial da coleção Lingerie Maternidade.	29.90	t	2026-01-13 19:54:30.088215+00	2026-01-13 19:54:30.088221+00	5
31	Kit 3 Calcinhas Gestante	Produto oficial da coleção Lingerie Maternidade.	69.90	t	2026-01-13 19:54:30.095004+00	2026-01-13 19:54:30.095009+00	5
32	Top Amamentação Esportivo	Produto oficial da coleção Lingerie Maternidade.	49.90	t	2026-01-13 19:54:30.099418+00	2026-01-13 19:54:30.099423+00	5
33	Camisola Maternidade Algodão	Produto oficial da coleção Pijamas e Camisolas.	79.90	t	2026-01-13 19:54:30.105209+00	2026-01-13 19:54:30.105217+00	6
34	Pijama Americano Gestante	Produto oficial da coleção Pijamas e Camisolas.	119.90	t	2026-01-13 19:54:30.11182+00	2026-01-13 19:54:30.111825+00	6
\.


--
-- TOC entry 3708 (class 0 OID 16612)
-- Dependencies: 249
-- Data for Name: product_productsupplier; Type: TABLE DATA; Schema: public; Owner: gesthar_user
--

COPY public.product_productsupplier (id, cost_price, added_at, updated_at, product_id, supplier_id) FROM stdin;
15	45.00	2026-01-13 19:54:29.973418+00	2026-01-13 19:54:29.973426+00	15	2
16	60.00	2026-01-13 19:54:29.987485+00	2026-01-13 19:54:29.987493+00	16	2
17	35.00	2026-01-13 19:54:29.995152+00	2026-01-13 19:54:29.995157+00	17	2
18	40.00	2026-01-13 19:54:30.003682+00	2026-01-13 19:54:30.003687+00	18	2
19	25.00	2026-01-13 19:54:30.015377+00	2026-01-13 19:54:30.015382+00	19	2
20	55.00	2026-01-13 19:54:30.026872+00	2026-01-13 19:54:30.026877+00	20	2
21	30.00	2026-01-13 19:54:30.033106+00	2026-01-13 19:54:30.03311+00	21	2
22	70.00	2026-01-13 19:54:30.041063+00	2026-01-13 19:54:30.041068+00	22	2
23	35.00	2026-01-13 19:54:30.044682+00	2026-01-13 19:54:30.044687+00	23	2
24	15.00	2026-01-13 19:54:30.049294+00	2026-01-13 19:54:30.049299+00	24	2
25	45.00	2026-01-13 19:54:30.056842+00	2026-01-13 19:54:30.056847+00	25	2
26	90.00	2026-01-13 19:54:30.064093+00	2026-01-13 19:54:30.064098+00	26	2
27	75.00	2026-01-13 19:54:30.070467+00	2026-01-13 19:54:30.070475+00	27	2
28	25.00	2026-01-13 19:54:30.075629+00	2026-01-13 19:54:30.075636+00	28	2
29	40.00	2026-01-13 19:54:30.084346+00	2026-01-13 19:54:30.084351+00	29	2
30	12.00	2026-01-13 19:54:30.089066+00	2026-01-13 19:54:30.089071+00	30	2
31	30.00	2026-01-13 19:54:30.095816+00	2026-01-13 19:54:30.09582+00	31	2
32	20.00	2026-01-13 19:54:30.100203+00	2026-01-13 19:54:30.100207+00	32	2
33	35.00	2026-01-13 19:54:30.106048+00	2026-01-13 19:54:30.106053+00	33	2
34	55.00	2026-01-13 19:54:30.11477+00	2026-01-13 19:54:30.114779+00	34	2
\.


--
-- TOC entry 3706 (class 0 OID 16602)
-- Dependencies: 247
-- Data for Name: product_productvariation; Type: TABLE DATA; Schema: public; Owner: gesthar_user
--

COPY public.product_productvariation (id, sku, stock, minimum_stock, is_active, created_at, updated_at, color_id, product_id, size_id) FROM stdin;
115	VESMIC-P-P-SCI	13	3	t	2026-01-13 19:54:29.974559+00	2026-01-13 19:54:29.974565+00	11	15	11
116	VESMIC-P-M-58R	26	3	t	2026-01-13 19:54:29.975761+00	2026-01-13 19:54:29.975768+00	11	15	12
117	VESMIC-P-G-S98	16	3	t	2026-01-13 19:54:29.976668+00	2026-01-13 19:54:29.976675+00	11	15	13
118	VESMIC-P-GG-PYA	8	3	t	2026-01-13 19:54:29.977438+00	2026-01-13 19:54:29.977445+00	11	15	14
119	VESMIC-V-P-OWO	23	3	t	2026-01-13 19:54:29.97833+00	2026-01-13 19:54:29.978335+00	17	15	11
120	VESMIC-V-M-DW1	26	3	t	2026-01-13 19:54:29.979184+00	2026-01-13 19:54:29.979189+00	17	15	12
121	VESMIC-V-G-97Q	30	3	t	2026-01-13 19:54:29.979946+00	2026-01-13 19:54:29.979951+00	17	15	13
122	VESMIC-V-GG-ZJW	16	3	t	2026-01-13 19:54:29.980711+00	2026-01-13 19:54:29.980716+00	17	15	14
123	VESMIC-CM-P-913	22	3	t	2026-01-13 19:54:29.981502+00	2026-01-13 19:54:29.981507+00	16	15	11
124	VESMIC-CM-M-JWX	15	3	t	2026-01-13 19:54:29.982264+00	2026-01-13 19:54:29.982269+00	16	15	12
125	VESMIC-CM-G-D40	16	3	t	2026-01-13 19:54:29.982975+00	2026-01-13 19:54:29.98298+00	16	15	13
126	VESMIC-CM-GG-78S	29	3	t	2026-01-13 19:54:29.983883+00	2026-01-13 19:54:29.983889+00	16	15	14
127	CALJECE-AM-38-IXE	5	3	t	2026-01-13 19:54:29.988241+00	2026-01-13 19:54:29.98825+00	15	16	16
128	CALJECE-AM-40-IC0	29	3	t	2026-01-13 19:54:29.989248+00	2026-01-13 19:54:29.989255+00	15	16	17
129	CALJECE-AM-42-LY6	23	3	t	2026-01-13 19:54:29.990098+00	2026-01-13 19:54:29.990103+00	15	16	18
130	CALJECE-AM-44-GN5	7	3	t	2026-01-13 19:54:29.990906+00	2026-01-13 19:54:29.990915+00	15	16	19
131	CALJECE-AM-46-YHX	23	3	t	2026-01-13 19:54:29.991738+00	2026-01-13 19:54:29.991743+00	15	16	20
132	BATSOV-B-P-3BF	29	3	t	2026-01-13 19:54:29.995927+00	2026-01-13 19:54:29.995933+00	12	17	11
133	BATSOV-B-M-MSS	8	3	t	2026-01-13 19:54:29.99679+00	2026-01-13 19:54:29.996795+00	12	17	12
134	BATSOV-B-G-P9J	17	3	t	2026-01-13 19:54:29.997576+00	2026-01-13 19:54:29.997581+00	12	17	13
135	BATSOV-EF-P-QR5	21	3	t	2026-01-13 19:54:29.998372+00	2026-01-13 19:54:29.998377+00	19	17	11
136	BATSOV-EF-M-VQS	18	3	t	2026-01-13 19:54:29.999137+00	2026-01-13 19:54:29.999142+00	19	17	12
137	BATSOV-EF-G-9DS	5	3	t	2026-01-13 19:54:29.999916+00	2026-01-13 19:54:29.999921+00	19	17	13
138	SHOGEL-B-P-3K3	9	3	t	2026-01-13 19:54:30.004386+00	2026-01-13 19:54:30.004393+00	13	18	11
139	SHOGEL-B-M-AO9	14	3	t	2026-01-13 19:54:30.005198+00	2026-01-13 19:54:30.005205+00	13	18	12
140	SHOGEL-B-G-1SR	13	3	t	2026-01-13 19:54:30.006023+00	2026-01-13 19:54:30.00603+00	13	18	13
141	SHOGEL-B-GG-W71	18	3	t	2026-01-13 19:54:30.006756+00	2026-01-13 19:54:30.006763+00	13	18	14
142	SHOGEL-P-P-PS3	8	3	t	2026-01-13 19:54:30.0075+00	2026-01-13 19:54:30.007507+00	11	18	11
143	SHOGEL-P-M-THW	14	3	t	2026-01-13 19:54:30.008214+00	2026-01-13 19:54:30.008221+00	11	18	12
144	SHOGEL-P-G-XZK	26	3	t	2026-01-13 19:54:30.008921+00	2026-01-13 19:54:30.008928+00	11	18	13
145	SHOGEL-P-GG-48R	17	3	t	2026-01-13 19:54:30.009597+00	2026-01-13 19:54:30.009604+00	11	18	14
146	SHOGEL-VM-P-LX8	20	3	t	2026-01-13 19:54:30.010335+00	2026-01-13 19:54:30.010342+00	18	18	11
147	SHOGEL-VM-M-4OA	11	3	t	2026-01-13 19:54:30.011102+00	2026-01-13 19:54:30.011108+00	18	18	12
148	SHOGEL-VM-G-DOZ	26	3	t	2026-01-13 19:54:30.011725+00	2026-01-13 19:54:30.01173+00	18	18	13
149	SHOGEL-VM-GG-9AD	13	3	t	2026-01-13 19:54:30.012393+00	2026-01-13 19:54:30.012398+00	18	18	14
150	LEGGEB-P-P-6LE	11	3	t	2026-01-13 19:54:30.015956+00	2026-01-13 19:54:30.015961+00	11	19	11
151	LEGGEB-P-M-6DQ	23	3	t	2026-01-13 19:54:30.016558+00	2026-01-13 19:54:30.016562+00	11	19	12
152	LEGGEB-P-G-4S7	14	3	t	2026-01-13 19:54:30.017119+00	2026-01-13 19:54:30.017123+00	11	19	13
153	LEGGEB-P-GG-126	20	3	t	2026-01-13 19:54:30.017666+00	2026-01-13 19:54:30.01767+00	11	19	14
154	LEGGEB-P-XG-BKL	14	3	t	2026-01-13 19:54:30.018206+00	2026-01-13 19:54:30.018209+00	11	19	15
155	LEGGEB-CM-P-TS7	25	3	t	2026-01-13 19:54:30.018741+00	2026-01-13 19:54:30.018745+00	16	19	11
156	LEGGEB-CM-M-L7G	25	3	t	2026-01-13 19:54:30.019355+00	2026-01-13 19:54:30.01936+00	16	19	12
157	LEGGEB-CM-G-SAI	9	3	t	2026-01-13 19:54:30.019927+00	2026-01-13 19:54:30.019931+00	16	19	13
158	LEGGEB-CM-GG-UK8	25	3	t	2026-01-13 19:54:30.020484+00	2026-01-13 19:54:30.020488+00	16	19	14
159	LEGGEB-CM-XG-RZO	9	3	t	2026-01-13 19:54:30.021059+00	2026-01-13 19:54:30.021066+00	16	19	15
160	LEGGEB-AM-P-H6P	19	3	t	2026-01-13 19:54:30.02168+00	2026-01-13 19:54:30.021685+00	15	19	11
161	LEGGEB-AM-M-GJL	20	3	t	2026-01-13 19:54:30.022252+00	2026-01-13 19:54:30.022256+00	15	19	12
162	LEGGEB-AM-G-149	21	3	t	2026-01-13 19:54:30.022804+00	2026-01-13 19:54:30.022808+00	15	19	13
163	LEGGEB-AM-GG-OXT	30	3	t	2026-01-13 19:54:30.023455+00	2026-01-13 19:54:30.02346+00	15	19	14
164	LEGGEB-AM-XG-E8M	24	3	t	2026-01-13 19:54:30.024078+00	2026-01-13 19:54:30.024083+00	15	19	15
165	MACLOM-P-M-7MA	30	3	t	2026-01-13 19:54:30.02753+00	2026-01-13 19:54:30.027535+00	11	20	12
166	MACLOM-P-G-H8R	27	3	t	2026-01-13 19:54:30.02812+00	2026-01-13 19:54:30.028124+00	11	20	13
167	MACLOM-P-GG-5J4	14	3	t	2026-01-13 19:54:30.028679+00	2026-01-13 19:54:30.028683+00	11	20	14
168	MACLOM-VM-M-HUL	20	3	t	2026-01-13 19:54:30.029226+00	2026-01-13 19:54:30.02923+00	18	20	12
169	MACLOM-VM-G-60X	11	3	t	2026-01-13 19:54:30.029776+00	2026-01-13 19:54:30.029779+00	18	20	13
170	MACLOM-VM-GG-ADR	8	3	t	2026-01-13 19:54:30.030322+00	2026-01-13 19:54:30.030326+00	18	20	14
171	BLUAMT-RB-P-6OE	9	3	t	2026-01-13 19:54:30.033794+00	2026-01-13 19:54:30.033799+00	14	21	11
172	BLUAMT-RB-M-LY5	16	3	t	2026-01-13 19:54:30.034401+00	2026-01-13 19:54:30.034405+00	14	21	12
173	BLUAMT-RB-G-QO3	12	3	t	2026-01-13 19:54:30.034976+00	2026-01-13 19:54:30.03498+00	14	21	13
174	BLUAMT-RB-GG-O74	26	3	t	2026-01-13 19:54:30.0355+00	2026-01-13 19:54:30.035506+00	14	21	14
175	BLUAMT-B-P-TFK	11	3	t	2026-01-13 19:54:30.035974+00	2026-01-13 19:54:30.03598+00	12	21	11
176	BLUAMT-B-M-4LF	24	3	t	2026-01-13 19:54:30.0364+00	2026-01-13 19:54:30.036405+00	12	21	12
177	BLUAMT-B-G-OKL	25	3	t	2026-01-13 19:54:30.036807+00	2026-01-13 19:54:30.036812+00	12	21	13
178	BLUAMT-B-GG-E0U	17	3	t	2026-01-13 19:54:30.037205+00	2026-01-13 19:54:30.03721+00	12	21	14
179	BLUAMT-L-P-LDZ	8	3	t	2026-01-13 19:54:30.037686+00	2026-01-13 19:54:30.037691+00	20	21	11
180	BLUAMT-L-M-3JV	13	3	t	2026-01-13 19:54:30.038137+00	2026-01-13 19:54:30.038141+00	20	21	12
181	BLUAMT-L-G-TFA	17	3	t	2026-01-13 19:54:30.03859+00	2026-01-13 19:54:30.038595+00	20	21	13
182	BLUAMT-L-GG-O2A	27	3	t	2026-01-13 19:54:30.039012+00	2026-01-13 19:54:30.039017+00	20	21	14
183	VESLOE-EF-P-64M	30	3	t	2026-01-13 19:54:30.041461+00	2026-01-13 19:54:30.041466+00	19	22	11
184	VESLOE-EF-M-90P	26	3	t	2026-01-13 19:54:30.041875+00	2026-01-13 19:54:30.041879+00	19	22	12
185	VESLOE-EF-G-7CD	30	3	t	2026-01-13 19:54:30.042455+00	2026-01-13 19:54:30.042461+00	19	22	13
186	SAIMIM-P-P-LKP	5	3	t	2026-01-13 19:54:30.045121+00	2026-01-13 19:54:30.045127+00	11	23	11
187	SAIMIM-P-M-6P4	29	3	t	2026-01-13 19:54:30.045567+00	2026-01-13 19:54:30.045572+00	11	23	12
188	SAIMIM-P-G-UVI	8	3	t	2026-01-13 19:54:30.046004+00	2026-01-13 19:54:30.046009+00	11	23	13
189	SAIMIM-L-P-LPL	22	3	t	2026-01-13 19:54:30.04643+00	2026-01-13 19:54:30.046434+00	20	23	11
190	SAIMIM-L-M-TQW	10	3	t	2026-01-13 19:54:30.046853+00	2026-01-13 19:54:30.046857+00	20	23	12
191	SAIMIM-L-G-CNT	20	3	t	2026-01-13 19:54:30.047334+00	2026-01-13 19:54:30.047339+00	20	23	13
192	REGBÁG-B-P-Q0Z	9	3	t	2026-01-13 19:54:30.049723+00	2026-01-13 19:54:30.049728+00	12	24	11
193	REGBÁG-B-M-RXF	12	3	t	2026-01-13 19:54:30.050169+00	2026-01-13 19:54:30.050174+00	12	24	12
194	REGBÁG-B-G-1PF	10	3	t	2026-01-13 19:54:30.050611+00	2026-01-13 19:54:30.050616+00	12	24	13
195	REGBÁG-B-GG-00M	23	3	t	2026-01-13 19:54:30.051062+00	2026-01-13 19:54:30.051067+00	12	24	14
196	REGBÁG-P-P-DR1	25	3	t	2026-01-13 19:54:30.051562+00	2026-01-13 19:54:30.051574+00	11	24	11
197	REGBÁG-P-M-T6R	20	3	t	2026-01-13 19:54:30.052029+00	2026-01-13 19:54:30.052033+00	11	24	12
198	REGBÁG-P-G-GDQ	25	3	t	2026-01-13 19:54:30.052438+00	2026-01-13 19:54:30.052443+00	11	24	13
199	REGBÁG-P-GG-15G	30	3	t	2026-01-13 19:54:30.052883+00	2026-01-13 19:54:30.052888+00	11	24	14
200	REGBÁG-CM-P-EY7	5	3	t	2026-01-13 19:54:30.053326+00	2026-01-13 19:54:30.053331+00	16	24	11
201	REGBÁG-CM-M-U7C	20	3	t	2026-01-13 19:54:30.053765+00	2026-01-13 19:54:30.053771+00	16	24	12
202	REGBÁG-CM-G-LM7	28	3	t	2026-01-13 19:54:30.05437+00	2026-01-13 19:54:30.054378+00	16	24	13
203	REGBÁG-CM-GG-X4V	12	3	t	2026-01-13 19:54:30.054934+00	2026-01-13 19:54:30.054939+00	16	24	14
204	CARALT-B-P-4BY	19	3	t	2026-01-13 19:54:30.057236+00	2026-01-13 19:54:30.057241+00	13	25	11
205	CARALT-B-M-OTD	18	3	t	2026-01-13 19:54:30.057641+00	2026-01-13 19:54:30.057645+00	13	25	12
206	CARALT-B-G-LGE	26	3	t	2026-01-13 19:54:30.058265+00	2026-01-13 19:54:30.058274+00	13	25	13
207	CARALT-CM-P-8H4	24	3	t	2026-01-13 19:54:30.058965+00	2026-01-13 19:54:30.05897+00	16	25	11
208	CARALT-CM-M-JTN	21	3	t	2026-01-13 19:54:30.059537+00	2026-01-13 19:54:30.059542+00	16	25	12
209	CARALT-CM-G-X37	20	3	t	2026-01-13 19:54:30.06011+00	2026-01-13 19:54:30.060115+00	16	25	13
210	CARALT-P-P-UGW	14	3	t	2026-01-13 19:54:30.060666+00	2026-01-13 19:54:30.060671+00	11	25	11
211	CARALT-P-M-ZYP	8	3	t	2026-01-13 19:54:30.061213+00	2026-01-13 19:54:30.061218+00	11	25	12
212	CARALT-P-G-J0Z	15	3	t	2026-01-13 19:54:30.061752+00	2026-01-13 19:54:30.061757+00	11	25	13
213	VESFEGR-AM-P-X6W	20	3	t	2026-01-13 19:54:30.064601+00	2026-01-13 19:54:30.064606+00	15	26	11
214	VESFEGR-AM-M-TWI	14	3	t	2026-01-13 19:54:30.065101+00	2026-01-13 19:54:30.065106+00	15	26	12
215	VESFEGR-AM-G-PLL	29	3	t	2026-01-13 19:54:30.065593+00	2026-01-13 19:54:30.065597+00	15	26	13
216	VESFEGR-AM-GG-VP6	10	3	t	2026-01-13 19:54:30.066074+00	2026-01-13 19:54:30.066082+00	15	26	14
217	VESFEGR-V-P-D7A	10	3	t	2026-01-13 19:54:30.066563+00	2026-01-13 19:54:30.066567+00	17	26	11
218	VESFEGR-V-M-MSL	29	3	t	2026-01-13 19:54:30.067064+00	2026-01-13 19:54:30.067069+00	17	26	12
219	VESFEGR-V-G-V8I	15	3	t	2026-01-13 19:54:30.06768+00	2026-01-13 19:54:30.067685+00	17	26	13
220	VESFEGR-V-GG-2UF	18	3	t	2026-01-13 19:54:30.068191+00	2026-01-13 19:54:30.068202+00	17	26	14
222	JARJEG-AM-40-U0J	9	3	t	2026-01-13 19:54:30.071858+00	2026-01-13 19:54:30.071862+00	15	27	17
223	JARJEG-AM-42-RZN	8	3	t	2026-01-13 19:54:30.07241+00	2026-01-13 19:54:30.072414+00	15	27	18
224	JARJEG-AM-44-122	19	3	t	2026-01-13 19:54:30.072938+00	2026-01-13 19:54:30.072942+00	15	27	19
225	SUTAMR-B-M-3RB	12	3	t	2026-01-13 19:54:30.076277+00	2026-01-13 19:54:30.076285+00	12	28	12
226	SUTAMR-B-G-6SQ	8	3	t	2026-01-13 19:54:30.076901+00	2026-01-13 19:54:30.076905+00	12	28	13
227	SUTAMR-B-GG-6FV	26	3	t	2026-01-13 19:54:30.077428+00	2026-01-13 19:54:30.077432+00	12	28	14
228	SUTAMR-B-M-0WG	7	3	t	2026-01-13 19:54:30.077927+00	2026-01-13 19:54:30.077931+00	13	28	12
229	SUTAMR-B-G-E9T	27	3	t	2026-01-13 19:54:30.078422+00	2026-01-13 19:54:30.078426+00	13	28	13
230	SUTAMR-B-GG-HB6	29	3	t	2026-01-13 19:54:30.078906+00	2026-01-13 19:54:30.07891+00	13	28	14
231	SUTAMR-P-M-QAV	22	3	t	2026-01-13 19:54:30.079429+00	2026-01-13 19:54:30.079433+00	11	28	12
232	SUTAMR-P-G-6TA	28	3	t	2026-01-13 19:54:30.07994+00	2026-01-13 19:54:30.079944+00	11	28	13
233	SUTAMR-P-GG-B25	29	3	t	2026-01-13 19:54:30.080436+00	2026-01-13 19:54:30.08044+00	11	28	14
234	SUTAMR-RB-M-RPD	30	3	t	2026-01-13 19:54:30.080935+00	2026-01-13 19:54:30.080943+00	14	28	12
235	SUTAMR-RB-G-ST3	17	3	t	2026-01-13 19:54:30.081435+00	2026-01-13 19:54:30.081439+00	14	28	13
236	SUTAMR-RB-GG-P5D	24	3	t	2026-01-13 19:54:30.081934+00	2026-01-13 19:54:30.081939+00	14	28	14
237	CINPÓM-B-P-QIV	19	3	t	2026-01-13 19:54:30.084852+00	2026-01-13 19:54:30.084856+00	13	29	11
238	CINPÓM-B-M-4BK	15	3	t	2026-01-13 19:54:30.085377+00	2026-01-13 19:54:30.085382+00	13	29	12
239	CINPÓM-B-G-2YU	18	3	t	2026-01-13 19:54:30.085909+00	2026-01-13 19:54:30.085913+00	13	29	13
240	CINPÓM-B-GG-F2E	24	3	t	2026-01-13 19:54:30.086442+00	2026-01-13 19:54:30.086446+00	13	29	14
241	CALPÓC-B-P-3TC	6	3	t	2026-01-13 19:54:30.089654+00	2026-01-13 19:54:30.089661+00	13	30	11
242	CALPÓC-B-M-DFN	14	3	t	2026-01-13 19:54:30.09028+00	2026-01-13 19:54:30.090288+00	13	30	12
243	CALPÓC-B-G-8Z6	21	3	t	2026-01-13 19:54:30.090854+00	2026-01-13 19:54:30.090859+00	13	30	13
244	CALPÓC-B-GG-8SJ	16	3	t	2026-01-13 19:54:30.091412+00	2026-01-13 19:54:30.091416+00	13	30	14
245	CALPÓC-P-P-T5V	28	3	t	2026-01-13 19:54:30.09194+00	2026-01-13 19:54:30.091944+00	11	30	11
246	CALPÓC-P-M-W8T	8	3	t	2026-01-13 19:54:30.092456+00	2026-01-13 19:54:30.09246+00	11	30	12
247	CALPÓC-P-G-FM6	14	3	t	2026-01-13 19:54:30.092984+00	2026-01-13 19:54:30.092988+00	11	30	13
248	CALPÓC-P-GG-UQF	23	3	t	2026-01-13 19:54:30.093513+00	2026-01-13 19:54:30.093517+00	11	30	14
249	KIT3CG-L-P-6UE	9	3	t	2026-01-13 19:54:30.096331+00	2026-01-13 19:54:30.096335+00	20	31	11
250	KIT3CG-L-M-0CR	15	3	t	2026-01-13 19:54:30.096863+00	2026-01-13 19:54:30.096868+00	20	31	12
251	KIT3CG-L-G-LFA	10	3	t	2026-01-13 19:54:30.097404+00	2026-01-13 19:54:30.097409+00	20	31	13
252	KIT3CG-L-GG-96U	6	3	t	2026-01-13 19:54:30.097922+00	2026-01-13 19:54:30.097927+00	20	31	14
253	TOPAME-CM-M-BJN	13	3	t	2026-01-13 19:54:30.100709+00	2026-01-13 19:54:30.100714+00	16	32	12
254	TOPAME-CM-G-GFM	21	3	t	2026-01-13 19:54:30.101291+00	2026-01-13 19:54:30.101295+00	16	32	13
255	TOPAME-CM-GG-S4X	23	3	t	2026-01-13 19:54:30.101817+00	2026-01-13 19:54:30.101821+00	16	32	14
256	TOPAME-P-M-NCA	14	3	t	2026-01-13 19:54:30.102351+00	2026-01-13 19:54:30.102356+00	11	32	12
257	TOPAME-P-G-V9U	9	3	t	2026-01-13 19:54:30.102859+00	2026-01-13 19:54:30.102864+00	11	32	13
258	TOPAME-P-GG-FPL	30	3	t	2026-01-13 19:54:30.103394+00	2026-01-13 19:54:30.103399+00	11	32	14
259	CAMMAA-CM-P-4H9	5	3	t	2026-01-13 19:54:30.106591+00	2026-01-13 19:54:30.106596+00	16	33	11
260	CAMMAA-CM-M-FDD	7	3	t	2026-01-13 19:54:30.107134+00	2026-01-13 19:54:30.107138+00	16	33	12
261	CAMMAA-CM-G-WKA	9	3	t	2026-01-13 19:54:30.10769+00	2026-01-13 19:54:30.107701+00	16	33	13
262	CAMMAA-CM-GG-B5O	28	3	t	2026-01-13 19:54:30.108227+00	2026-01-13 19:54:30.108231+00	16	33	14
263	CAMMAA-RB-P-51N	30	3	t	2026-01-13 19:54:30.108747+00	2026-01-13 19:54:30.108751+00	14	33	11
264	CAMMAA-RB-M-OJO	24	3	t	2026-01-13 19:54:30.109267+00	2026-01-13 19:54:30.109271+00	14	33	12
265	CAMMAA-RB-G-HSO	11	3	t	2026-01-13 19:54:30.109775+00	2026-01-13 19:54:30.109779+00	14	33	13
266	CAMMAA-RB-GG-5VL	22	3	t	2026-01-13 19:54:30.110311+00	2026-01-13 19:54:30.110315+00	14	33	14
267	PIJAMG-AM-P-12A	24	3	t	2026-01-13 19:54:30.118187+00	2026-01-13 19:54:30.118198+00	15	34	11
268	PIJAMG-AM-M-XAJ	16	3	t	2026-01-13 19:54:30.119206+00	2026-01-13 19:54:30.119214+00	15	34	12
269	PIJAMG-AM-G-QS9	28	3	t	2026-01-13 19:54:30.120017+00	2026-01-13 19:54:30.120024+00	15	34	13
270	PIJAMG-AM-GG-YOA	13	3	t	2026-01-13 19:54:30.12121+00	2026-01-13 19:54:30.121221+00	15	34	14
271	PIJAMG-V-P-BYE	24	3	t	2026-01-13 19:54:30.122191+00	2026-01-13 19:54:30.1222+00	17	34	11
272	PIJAMG-V-M-QGO	29	3	t	2026-01-13 19:54:30.122984+00	2026-01-13 19:54:30.122991+00	17	34	12
273	PIJAMG-V-G-DNK	17	3	t	2026-01-13 19:54:30.123799+00	2026-01-13 19:54:30.123806+00	17	34	13
274	PIJAMG-V-GG-0J6	10	3	t	2026-01-13 19:54:30.12454+00	2026-01-13 19:54:30.124547+00	17	34	14
221	JARJEG-AM-38-WGD	14	3	t	2026-01-13 19:54:30.071182+00	2026-01-13 20:58:46.474379+00	15	27	16
\.


--
-- TOC entry 3702 (class 0 OID 16586)
-- Dependencies: 243
-- Data for Name: product_size; Type: TABLE DATA; Schema: public; Owner: gesthar_user
--

COPY public.product_size (id, name, is_active) FROM stdin;
11	P	t
12	M	t
13	G	t
14	GG	t
15	XG	t
16	38	t
17	40	t
18	42	t
19	44	t
20	46	t
21	N/A	t
\.


--
-- TOC entry 3704 (class 0 OID 16594)
-- Dependencies: 245
-- Data for Name: product_supplier; Type: TABLE DATA; Schema: public; Owner: gesthar_user
--

COPY public.product_supplier (id, name, is_active) FROM stdin;
2	Fornecedor Gestante SP	t
\.


--
-- TOC entry 3710 (class 0 OID 16669)
-- Dependencies: 251
-- Data for Name: sales_cashregister; Type: TABLE DATA; Schema: public; Owner: gesthar_user
--

COPY public.sales_cashregister (id, is_active, deleted_at, opening_balance, closing_balance, opened_at, closed_at, status, user_id) FROM stdin;
1	t	\N	5.00	164.90	2026-01-13 20:58:36.272082+00	2026-01-13 20:58:56.966626+00	CLOSED	1
\.


--
-- TOC entry 3712 (class 0 OID 16675)
-- Dependencies: 253
-- Data for Name: sales_sale; Type: TABLE DATA; Schema: public; Owner: gesthar_user
--

COPY public.sales_sale (id, is_active, deleted_at, change_amount, created_at, updated_at, completed_at, status, gross_amount, discount_amount, net_amount, cash_register_session_id, customer_id, user_id) FROM stdin;
1	t	\N	0.00	2026-01-13 20:58:36.326136+00	2026-01-13 20:58:46.477631+00	2026-01-13 20:58:46.477547+00	COMPLETED	159.90	0.00	159.90	1	\N	1
2	t	\N	0.00	2026-01-13 20:58:46.505683+00	2026-01-13 20:58:46.505691+00	\N	DRAFT	0.00	0.00	0.00	1	\N	1
\.


--
-- TOC entry 3716 (class 0 OID 16687)
-- Dependencies: 257
-- Data for Name: sales_saleitem; Type: TABLE DATA; Schema: public; Owner: gesthar_user
--

COPY public.sales_saleitem (id, product_sku_snapshot, product_name_snapshot, quantity, unit_price, discount, total_price, sale_id, variation_id) FROM stdin;
1	JARJEG-AM-38-WGD	Jardineira Jeans Gestante - Azul Marinho - 38	1	159.90	0.00	159.90	1	221
\.


--
-- TOC entry 3714 (class 0 OID 16681)
-- Dependencies: 255
-- Data for Name: sales_salepayment; Type: TABLE DATA; Schema: public; Owner: gesthar_user
--

COPY public.sales_salepayment (id, method, amount, created_at, sale_id) FROM stdin;
1	DINHEIRO	159.90	2026-01-13 20:58:45.351081+00	1
\.


--
-- TOC entry 3719 (class 0 OID 16747)
-- Dependencies: 260
-- Data for Name: stock_stockmovement; Type: TABLE DATA; Schema: public; Owner: gesthar_user
--

COPY public.stock_stockmovement (id, movement_type, quantity, unit_price, movement_date, notes, product_variation_id, supplier_id, user_id) FROM stdin;
1	VENDA	1	\N	2026-01-13 20:58:46.475628+00	Venda PDV #1	221	\N	1
\.


--
-- TOC entry 3684 (class 0 OID 16452)
-- Dependencies: 225
-- Data for Name: user_usergesthar; Type: TABLE DATA; Schema: public; Owner: gesthar_user
--

COPY public.user_usergesthar (id, password, last_login, is_superuser, first_name, last_name, is_staff, is_active, date_joined, username, cpf, email, phone_number, hire_date, birth_date, exit_date, notes, role) FROM stdin;
1	pbkdf2_sha256$600000$RfhYOWbzRqJ15TWb1vxNRD$bGm7kfp2IF7un+zdBP9Qqha3gjlP83Y+9m6y2/ocu6U=	2026-01-13 19:56:00.908578+00	t			t	t	2026-01-13 19:55:27.976749+00	\N		usertest@gesthar.com.br	\N	\N	\N	\N	\N	\N
2	pbkdf2_sha256$600000$kYiCFMigXoZQYbDmaX8dT2$nHl3WjyTbhaBd7Q6wU1cVv6HW0hQg+xwdd0Rr6vN230=	2026-03-23 17:26:05.515118+00	t			t	t	2026-03-23 17:25:39.502222+00	\N		juniophb2004@gmail.com	\N	\N	\N	\N	\N	\N
\.


--
-- TOC entry 3686 (class 0 OID 16464)
-- Dependencies: 227
-- Data for Name: user_usergesthar_groups; Type: TABLE DATA; Schema: public; Owner: gesthar_user
--

COPY public.user_usergesthar_groups (id, usergesthar_id, group_id) FROM stdin;
\.


--
-- TOC entry 3688 (class 0 OID 16470)
-- Dependencies: 229
-- Data for Name: user_usergesthar_user_permissions; Type: TABLE DATA; Schema: public; Owner: gesthar_user
--

COPY public.user_usergesthar_user_permissions (id, usergesthar_id, permission_id) FROM stdin;
\.


--
-- TOC entry 3725 (class 0 OID 0)
-- Dependencies: 220
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gesthar_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- TOC entry 3726 (class 0 OID 0)
-- Dependencies: 222
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gesthar_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- TOC entry 3727 (class 0 OID 0)
-- Dependencies: 218
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gesthar_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 80, true);


--
-- TOC entry 3728 (class 0 OID 0)
-- Dependencies: 234
-- Name: customer_address_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gesthar_user
--

SELECT pg_catalog.setval('public.customer_address_id_seq', 1, false);


--
-- TOC entry 3729 (class 0 OID 0)
-- Dependencies: 232
-- Name: customer_customer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gesthar_user
--

SELECT pg_catalog.setval('public.customer_customer_id_seq', 1, false);


--
-- TOC entry 3730 (class 0 OID 0)
-- Dependencies: 230
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gesthar_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- TOC entry 3731 (class 0 OID 0)
-- Dependencies: 216
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gesthar_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 20, true);


--
-- TOC entry 3732 (class 0 OID 0)
-- Dependencies: 214
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gesthar_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 27, true);


--
-- TOC entry 3733 (class 0 OID 0)
-- Dependencies: 236
-- Name: product_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gesthar_user
--

SELECT pg_catalog.setval('public.product_category_id_seq', 6, true);


--
-- TOC entry 3734 (class 0 OID 0)
-- Dependencies: 238
-- Name: product_color_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gesthar_user
--

SELECT pg_catalog.setval('public.product_color_id_seq', 21, true);


--
-- TOC entry 3735 (class 0 OID 0)
-- Dependencies: 240
-- Name: product_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gesthar_user
--

SELECT pg_catalog.setval('public.product_product_id_seq', 34, true);


--
-- TOC entry 3736 (class 0 OID 0)
-- Dependencies: 248
-- Name: product_productsupplier_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gesthar_user
--

SELECT pg_catalog.setval('public.product_productsupplier_id_seq', 34, true);


--
-- TOC entry 3737 (class 0 OID 0)
-- Dependencies: 246
-- Name: product_productvariation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gesthar_user
--

SELECT pg_catalog.setval('public.product_productvariation_id_seq', 274, true);


--
-- TOC entry 3738 (class 0 OID 0)
-- Dependencies: 242
-- Name: product_size_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gesthar_user
--

SELECT pg_catalog.setval('public.product_size_id_seq', 21, true);


--
-- TOC entry 3739 (class 0 OID 0)
-- Dependencies: 244
-- Name: product_supplier_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gesthar_user
--

SELECT pg_catalog.setval('public.product_supplier_id_seq', 2, true);


--
-- TOC entry 3740 (class 0 OID 0)
-- Dependencies: 250
-- Name: sales_cashregister_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gesthar_user
--

SELECT pg_catalog.setval('public.sales_cashregister_id_seq', 1, true);


--
-- TOC entry 3741 (class 0 OID 0)
-- Dependencies: 252
-- Name: sales_sale_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gesthar_user
--

SELECT pg_catalog.setval('public.sales_sale_id_seq', 2, true);


--
-- TOC entry 3742 (class 0 OID 0)
-- Dependencies: 256
-- Name: sales_saleitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gesthar_user
--

SELECT pg_catalog.setval('public.sales_saleitem_id_seq', 1, true);


--
-- TOC entry 3743 (class 0 OID 0)
-- Dependencies: 254
-- Name: sales_salepayment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gesthar_user
--

SELECT pg_catalog.setval('public.sales_salepayment_id_seq', 1, true);


--
-- TOC entry 3744 (class 0 OID 0)
-- Dependencies: 259
-- Name: stock_stockmovement_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gesthar_user
--

SELECT pg_catalog.setval('public.stock_stockmovement_id_seq', 1, true);


--
-- TOC entry 3745 (class 0 OID 0)
-- Dependencies: 226
-- Name: user_usergesthar_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gesthar_user
--

SELECT pg_catalog.setval('public.user_usergesthar_groups_id_seq', 1, false);


--
-- TOC entry 3746 (class 0 OID 0)
-- Dependencies: 224
-- Name: user_usergesthar_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gesthar_user
--

SELECT pg_catalog.setval('public.user_usergesthar_id_seq', 2, true);


--
-- TOC entry 3747 (class 0 OID 0)
-- Dependencies: 228
-- Name: user_usergesthar_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gesthar_user
--

SELECT pg_catalog.setval('public.user_usergesthar_user_permissions_id_seq', 1, false);


--
-- TOC entry 3396 (class 2606 OID 16449)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 3401 (class 2606 OID 16435)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 3404 (class 2606 OID 16424)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 3398 (class 2606 OID 16416)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 3391 (class 2606 OID 16426)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 3393 (class 2606 OID 16410)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 3436 (class 2606 OID 16545)
-- Name: customer_address customer_address_pkey; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.customer_address
    ADD CONSTRAINT customer_address_pkey PRIMARY KEY (id);


--
-- TOC entry 3428 (class 2606 OID 16555)
-- Name: customer_customer customer_customer_cpf_key; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.customer_customer
    ADD CONSTRAINT customer_customer_cpf_key UNIQUE (cpf_cnpj);


--
-- TOC entry 3431 (class 2606 OID 16537)
-- Name: customer_customer customer_customer_email_key; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.customer_customer
    ADD CONSTRAINT customer_customer_email_key UNIQUE (email);


--
-- TOC entry 3433 (class 2606 OID 16533)
-- Name: customer_customer customer_customer_pkey; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.customer_customer
    ADD CONSTRAINT customer_customer_pkey PRIMARY KEY (id);


--
-- TOC entry 3424 (class 2606 OID 16513)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 3386 (class 2606 OID 16404)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 3388 (class 2606 OID 16402)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 3384 (class 2606 OID 16396)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 3498 (class 2606 OID 16743)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 3474 (class 2606 OID 16621)
-- Name: product_productsupplier prod_supplier_unique_link_uq; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.product_productsupplier
    ADD CONSTRAINT prod_supplier_unique_link_uq UNIQUE (product_id, supplier_id);


--
-- TOC entry 3439 (class 2606 OID 16566)
-- Name: product_category product_category_name_key; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.product_category
    ADD CONSTRAINT product_category_name_key UNIQUE (name);


--
-- TOC entry 3441 (class 2606 OID 16564)
-- Name: product_category product_category_pkey; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.product_category
    ADD CONSTRAINT product_category_pkey PRIMARY KEY (id);


--
-- TOC entry 3444 (class 2606 OID 16574)
-- Name: product_color product_color_name_key; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.product_color
    ADD CONSTRAINT product_color_name_key UNIQUE (name);


--
-- TOC entry 3446 (class 2606 OID 16572)
-- Name: product_color product_color_pkey; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.product_color
    ADD CONSTRAINT product_color_pkey PRIMARY KEY (id);


--
-- TOC entry 3450 (class 2606 OID 16584)
-- Name: product_product product_product_name_key; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.product_product
    ADD CONSTRAINT product_product_name_key UNIQUE (name);


--
-- TOC entry 3452 (class 2606 OID 16582)
-- Name: product_product product_product_pkey; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.product_product
    ADD CONSTRAINT product_product_pkey PRIMARY KEY (id);


--
-- TOC entry 3476 (class 2606 OID 16616)
-- Name: product_productsupplier product_productsupplier_pkey; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.product_productsupplier
    ADD CONSTRAINT product_productsupplier_pkey PRIMARY KEY (id);


--
-- TOC entry 3465 (class 2606 OID 16608)
-- Name: product_productvariation product_productvariation_pkey; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.product_productvariation
    ADD CONSTRAINT product_productvariation_pkey PRIMARY KEY (id);


--
-- TOC entry 3470 (class 2606 OID 16610)
-- Name: product_productvariation product_productvariation_sku_key; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.product_productvariation
    ADD CONSTRAINT product_productvariation_sku_key UNIQUE (sku);


--
-- TOC entry 3455 (class 2606 OID 16665)
-- Name: product_size product_size_name_fa291da2_uniq; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.product_size
    ADD CONSTRAINT product_size_name_fa291da2_uniq UNIQUE (name);


--
-- TOC entry 3457 (class 2606 OID 16590)
-- Name: product_size product_size_pkey; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.product_size
    ADD CONSTRAINT product_size_pkey PRIMARY KEY (id);


--
-- TOC entry 3460 (class 2606 OID 16600)
-- Name: product_supplier product_supplier_name_key; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.product_supplier
    ADD CONSTRAINT product_supplier_name_key UNIQUE (name);


--
-- TOC entry 3462 (class 2606 OID 16598)
-- Name: product_supplier product_supplier_pkey; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.product_supplier
    ADD CONSTRAINT product_supplier_pkey PRIMARY KEY (id);


--
-- TOC entry 3480 (class 2606 OID 16673)
-- Name: sales_cashregister sales_cashregister_pkey; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.sales_cashregister
    ADD CONSTRAINT sales_cashregister_pkey PRIMARY KEY (id);


--
-- TOC entry 3485 (class 2606 OID 16679)
-- Name: sales_sale sales_sale_pkey; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.sales_sale
    ADD CONSTRAINT sales_sale_pkey PRIMARY KEY (id);


--
-- TOC entry 3491 (class 2606 OID 16692)
-- Name: sales_saleitem sales_saleitem_pkey; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.sales_saleitem
    ADD CONSTRAINT sales_saleitem_pkey PRIMARY KEY (id);


--
-- TOC entry 3488 (class 2606 OID 16685)
-- Name: sales_salepayment sales_salepayment_pkey; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.sales_salepayment
    ADD CONSTRAINT sales_salepayment_pkey PRIMARY KEY (id);


--
-- TOC entry 3501 (class 2606 OID 16754)
-- Name: stock_stockmovement stock_stockmovement_pkey; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.stock_stockmovement
    ADD CONSTRAINT stock_stockmovement_pkey PRIMARY KEY (id);


--
-- TOC entry 3472 (class 2606 OID 16619)
-- Name: product_productvariation unique_product_color_size; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.product_productvariation
    ADD CONSTRAINT unique_product_color_size UNIQUE (product_id, color_id, size_id);


--
-- TOC entry 3495 (class 2606 OID 16694)
-- Name: sales_saleitem unique_variation_per_sale; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.sales_saleitem
    ADD CONSTRAINT unique_variation_per_sale UNIQUE (sale_id, variation_id);


--
-- TOC entry 3407 (class 2606 OID 16462)
-- Name: user_usergesthar user_usergesthar_email_key; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.user_usergesthar
    ADD CONSTRAINT user_usergesthar_email_key UNIQUE (email);


--
-- TOC entry 3412 (class 2606 OID 16468)
-- Name: user_usergesthar_groups user_usergesthar_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.user_usergesthar_groups
    ADD CONSTRAINT user_usergesthar_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 3415 (class 2606 OID 16478)
-- Name: user_usergesthar_groups user_usergesthar_groups_usergesthar_id_group_id_a3d3ecc0_uniq; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.user_usergesthar_groups
    ADD CONSTRAINT user_usergesthar_groups_usergesthar_id_group_id_a3d3ecc0_uniq UNIQUE (usergesthar_id, group_id);


--
-- TOC entry 3409 (class 2606 OID 16458)
-- Name: user_usergesthar user_usergesthar_pkey; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.user_usergesthar
    ADD CONSTRAINT user_usergesthar_pkey PRIMARY KEY (id);


--
-- TOC entry 3417 (class 2606 OID 16492)
-- Name: user_usergesthar_user_permissions user_usergesthar_user_pe_usergesthar_id_permissio_36dacf1f_uniq; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.user_usergesthar_user_permissions
    ADD CONSTRAINT user_usergesthar_user_pe_usergesthar_id_permissio_36dacf1f_uniq UNIQUE (usergesthar_id, permission_id);


--
-- TOC entry 3420 (class 2606 OID 16474)
-- Name: user_usergesthar_user_permissions user_usergesthar_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.user_usergesthar_user_permissions
    ADD CONSTRAINT user_usergesthar_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 3394 (class 1259 OID 16450)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 3399 (class 1259 OID 16446)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 3402 (class 1259 OID 16447)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 3389 (class 1259 OID 16432)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 3434 (class 1259 OID 16553)
-- Name: customer_address_customer_id_0bcda8c7; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX customer_address_customer_id_0bcda8c7 ON public.customer_address USING btree (customer_id);


--
-- TOC entry 3426 (class 1259 OID 16556)
-- Name: customer_customer_cpf_e6545718_like; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX customer_customer_cpf_e6545718_like ON public.customer_customer USING btree (cpf_cnpj varchar_pattern_ops);


--
-- TOC entry 3429 (class 1259 OID 16547)
-- Name: customer_customer_email_3a520497_like; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX customer_customer_email_3a520497_like ON public.customer_customer USING btree (email varchar_pattern_ops);


--
-- TOC entry 3422 (class 1259 OID 16524)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 3425 (class 1259 OID 16525)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 3496 (class 1259 OID 16745)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 3499 (class 1259 OID 16744)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 3437 (class 1259 OID 16622)
-- Name: product_category_name_905278b8_like; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX product_category_name_905278b8_like ON public.product_category USING btree (name varchar_pattern_ops);


--
-- TOC entry 3442 (class 1259 OID 16623)
-- Name: product_color_name_131bf32d_like; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX product_color_name_131bf32d_like ON public.product_color USING btree (name varchar_pattern_ops);


--
-- TOC entry 3447 (class 1259 OID 16630)
-- Name: product_product_category_id_0c725779; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX product_product_category_id_0c725779 ON public.product_product USING btree (category_id);


--
-- TOC entry 3448 (class 1259 OID 16629)
-- Name: product_product_name_04ac86ce_like; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX product_product_name_04ac86ce_like ON public.product_product USING btree (name varchar_pattern_ops);


--
-- TOC entry 3477 (class 1259 OID 16662)
-- Name: product_productsupplier_product_id_69a92b9c; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX product_productsupplier_product_id_69a92b9c ON public.product_productsupplier USING btree (product_id);


--
-- TOC entry 3478 (class 1259 OID 16663)
-- Name: product_productsupplier_supplier_id_5b4eff72; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX product_productsupplier_supplier_id_5b4eff72 ON public.product_productsupplier USING btree (supplier_id);


--
-- TOC entry 3463 (class 1259 OID 16649)
-- Name: product_productvariation_color_id_8eece0d4; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX product_productvariation_color_id_8eece0d4 ON public.product_productvariation USING btree (color_id);


--
-- TOC entry 3466 (class 1259 OID 16650)
-- Name: product_productvariation_product_id_58c992e2; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX product_productvariation_product_id_58c992e2 ON public.product_productvariation USING btree (product_id);


--
-- TOC entry 3467 (class 1259 OID 16651)
-- Name: product_productvariation_size_id_741a6022; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX product_productvariation_size_id_741a6022 ON public.product_productvariation USING btree (size_id);


--
-- TOC entry 3468 (class 1259 OID 16648)
-- Name: product_productvariation_sku_0935cc39_like; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX product_productvariation_sku_0935cc39_like ON public.product_productvariation USING btree (sku varchar_pattern_ops);


--
-- TOC entry 3453 (class 1259 OID 16666)
-- Name: product_size_name_fa291da2_like; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX product_size_name_fa291da2_like ON public.product_size USING btree (name varchar_pattern_ops);


--
-- TOC entry 3458 (class 1259 OID 16632)
-- Name: product_supplier_name_b1a1b194_like; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX product_supplier_name_b1a1b194_like ON public.product_supplier USING btree (name varchar_pattern_ops);


--
-- TOC entry 3481 (class 1259 OID 16700)
-- Name: sales_cashregister_user_id_85e89ba5; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX sales_cashregister_user_id_85e89ba5 ON public.sales_cashregister USING btree (user_id);


--
-- TOC entry 3482 (class 1259 OID 16716)
-- Name: sales_sale_cash_register_session_id_7aedbd6b; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX sales_sale_cash_register_session_id_7aedbd6b ON public.sales_sale USING btree (cash_register_session_id);


--
-- TOC entry 3483 (class 1259 OID 16717)
-- Name: sales_sale_customer_id_2d66a408; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX sales_sale_customer_id_2d66a408 ON public.sales_sale USING btree (customer_id);


--
-- TOC entry 3486 (class 1259 OID 16718)
-- Name: sales_sale_user_id_c0f47f66; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX sales_sale_user_id_c0f47f66 ON public.sales_sale USING btree (user_id);


--
-- TOC entry 3492 (class 1259 OID 16735)
-- Name: sales_saleitem_sale_id_56e67045; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX sales_saleitem_sale_id_56e67045 ON public.sales_saleitem USING btree (sale_id);


--
-- TOC entry 3493 (class 1259 OID 16736)
-- Name: sales_saleitem_variation_id_beafae52; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX sales_saleitem_variation_id_beafae52 ON public.sales_saleitem USING btree (variation_id);


--
-- TOC entry 3489 (class 1259 OID 16724)
-- Name: sales_salepayment_sale_id_894e0b7b; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX sales_salepayment_sale_id_894e0b7b ON public.sales_salepayment USING btree (sale_id);


--
-- TOC entry 3502 (class 1259 OID 16770)
-- Name: stock_stockmovement_product_variation_id_cfef142a; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX stock_stockmovement_product_variation_id_cfef142a ON public.stock_stockmovement USING btree (product_variation_id);


--
-- TOC entry 3503 (class 1259 OID 16771)
-- Name: stock_stockmovement_supplier_id_81a2e97b; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX stock_stockmovement_supplier_id_81a2e97b ON public.stock_stockmovement USING btree (supplier_id);


--
-- TOC entry 3504 (class 1259 OID 16772)
-- Name: stock_stockmovement_user_id_85210c95; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX stock_stockmovement_user_id_85210c95 ON public.stock_stockmovement USING btree (user_id);


--
-- TOC entry 3405 (class 1259 OID 16476)
-- Name: user_usergesthar_email_ab9ee121_like; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX user_usergesthar_email_ab9ee121_like ON public.user_usergesthar USING btree (email varchar_pattern_ops);


--
-- TOC entry 3410 (class 1259 OID 16490)
-- Name: user_usergesthar_groups_group_id_d7c074ea; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX user_usergesthar_groups_group_id_d7c074ea ON public.user_usergesthar_groups USING btree (group_id);


--
-- TOC entry 3413 (class 1259 OID 16489)
-- Name: user_usergesthar_groups_usergesthar_id_4f0e0ccf; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX user_usergesthar_groups_usergesthar_id_4f0e0ccf ON public.user_usergesthar_groups USING btree (usergesthar_id);


--
-- TOC entry 3418 (class 1259 OID 16504)
-- Name: user_usergesthar_user_permissions_permission_id_9d17aa3b; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX user_usergesthar_user_permissions_permission_id_9d17aa3b ON public.user_usergesthar_user_permissions USING btree (permission_id);


--
-- TOC entry 3421 (class 1259 OID 16503)
-- Name: user_usergesthar_user_permissions_usergesthar_id_da638d82; Type: INDEX; Schema: public; Owner: gesthar_user
--

CREATE INDEX user_usergesthar_user_permissions_usergesthar_id_da638d82 ON public.user_usergesthar_user_permissions USING btree (usergesthar_id);


--
-- TOC entry 3506 (class 2606 OID 16441)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3507 (class 2606 OID 16436)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3505 (class 2606 OID 16427)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3514 (class 2606 OID 16548)
-- Name: customer_address customer_address_customer_id_0bcda8c7_fk_customer_customer_id; Type: FK CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.customer_address
    ADD CONSTRAINT customer_address_customer_id_0bcda8c7_fk_customer_customer_id FOREIGN KEY (customer_id) REFERENCES public.customer_customer(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3512 (class 2606 OID 16514)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3513 (class 2606 OID 16519)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_user_usergesthar_id; Type: FK CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_user_usergesthar_id FOREIGN KEY (user_id) REFERENCES public.user_usergesthar(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3515 (class 2606 OID 16624)
-- Name: product_product product_product_category_id_0c725779_fk_product_category_id; Type: FK CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.product_product
    ADD CONSTRAINT product_product_category_id_0c725779_fk_product_category_id FOREIGN KEY (category_id) REFERENCES public.product_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3519 (class 2606 OID 16652)
-- Name: product_productsupplier product_productsuppl_product_id_69a92b9c_fk_product_p; Type: FK CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.product_productsupplier
    ADD CONSTRAINT product_productsuppl_product_id_69a92b9c_fk_product_p FOREIGN KEY (product_id) REFERENCES public.product_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3520 (class 2606 OID 16657)
-- Name: product_productsupplier product_productsuppl_supplier_id_5b4eff72_fk_product_s; Type: FK CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.product_productsupplier
    ADD CONSTRAINT product_productsuppl_supplier_id_5b4eff72_fk_product_s FOREIGN KEY (supplier_id) REFERENCES public.product_supplier(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3516 (class 2606 OID 16638)
-- Name: product_productvariation product_productvaria_product_id_58c992e2_fk_product_p; Type: FK CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.product_productvariation
    ADD CONSTRAINT product_productvaria_product_id_58c992e2_fk_product_p FOREIGN KEY (product_id) REFERENCES public.product_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3517 (class 2606 OID 16633)
-- Name: product_productvariation product_productvariation_color_id_8eece0d4_fk_product_color_id; Type: FK CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.product_productvariation
    ADD CONSTRAINT product_productvariation_color_id_8eece0d4_fk_product_color_id FOREIGN KEY (color_id) REFERENCES public.product_color(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3518 (class 2606 OID 16643)
-- Name: product_productvariation product_productvariation_size_id_741a6022_fk_product_size_id; Type: FK CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.product_productvariation
    ADD CONSTRAINT product_productvariation_size_id_741a6022_fk_product_size_id FOREIGN KEY (size_id) REFERENCES public.product_size(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3521 (class 2606 OID 16695)
-- Name: sales_cashregister sales_cashregister_user_id_85e89ba5_fk_user_usergesthar_id; Type: FK CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.sales_cashregister
    ADD CONSTRAINT sales_cashregister_user_id_85e89ba5_fk_user_usergesthar_id FOREIGN KEY (user_id) REFERENCES public.user_usergesthar(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3522 (class 2606 OID 16701)
-- Name: sales_sale sales_sale_cash_register_sessio_7aedbd6b_fk_sales_cas; Type: FK CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.sales_sale
    ADD CONSTRAINT sales_sale_cash_register_sessio_7aedbd6b_fk_sales_cas FOREIGN KEY (cash_register_session_id) REFERENCES public.sales_cashregister(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3523 (class 2606 OID 16706)
-- Name: sales_sale sales_sale_customer_id_2d66a408_fk_customer_customer_id; Type: FK CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.sales_sale
    ADD CONSTRAINT sales_sale_customer_id_2d66a408_fk_customer_customer_id FOREIGN KEY (customer_id) REFERENCES public.customer_customer(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3524 (class 2606 OID 16711)
-- Name: sales_sale sales_sale_user_id_c0f47f66_fk_user_usergesthar_id; Type: FK CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.sales_sale
    ADD CONSTRAINT sales_sale_user_id_c0f47f66_fk_user_usergesthar_id FOREIGN KEY (user_id) REFERENCES public.user_usergesthar(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3526 (class 2606 OID 16725)
-- Name: sales_saleitem sales_saleitem_sale_id_56e67045_fk_sales_sale_id; Type: FK CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.sales_saleitem
    ADD CONSTRAINT sales_saleitem_sale_id_56e67045_fk_sales_sale_id FOREIGN KEY (sale_id) REFERENCES public.sales_sale(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3527 (class 2606 OID 16730)
-- Name: sales_saleitem sales_saleitem_variation_id_beafae52_fk_product_p; Type: FK CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.sales_saleitem
    ADD CONSTRAINT sales_saleitem_variation_id_beafae52_fk_product_p FOREIGN KEY (variation_id) REFERENCES public.product_productvariation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3525 (class 2606 OID 16719)
-- Name: sales_salepayment sales_salepayment_sale_id_894e0b7b_fk_sales_sale_id; Type: FK CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.sales_salepayment
    ADD CONSTRAINT sales_salepayment_sale_id_894e0b7b_fk_sales_sale_id FOREIGN KEY (sale_id) REFERENCES public.sales_sale(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3528 (class 2606 OID 16755)
-- Name: stock_stockmovement stock_stockmovement_product_variation_id_cfef142a_fk_product_p; Type: FK CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.stock_stockmovement
    ADD CONSTRAINT stock_stockmovement_product_variation_id_cfef142a_fk_product_p FOREIGN KEY (product_variation_id) REFERENCES public.product_productvariation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3529 (class 2606 OID 16760)
-- Name: stock_stockmovement stock_stockmovement_supplier_id_81a2e97b_fk_product_supplier_id; Type: FK CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.stock_stockmovement
    ADD CONSTRAINT stock_stockmovement_supplier_id_81a2e97b_fk_product_supplier_id FOREIGN KEY (supplier_id) REFERENCES public.product_supplier(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3530 (class 2606 OID 16765)
-- Name: stock_stockmovement stock_stockmovement_user_id_85210c95_fk_user_usergesthar_id; Type: FK CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.stock_stockmovement
    ADD CONSTRAINT stock_stockmovement_user_id_85210c95_fk_user_usergesthar_id FOREIGN KEY (user_id) REFERENCES public.user_usergesthar(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3508 (class 2606 OID 16479)
-- Name: user_usergesthar_groups user_usergesthar_gro_usergesthar_id_4f0e0ccf_fk_user_user; Type: FK CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.user_usergesthar_groups
    ADD CONSTRAINT user_usergesthar_gro_usergesthar_id_4f0e0ccf_fk_user_user FOREIGN KEY (usergesthar_id) REFERENCES public.user_usergesthar(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3509 (class 2606 OID 16484)
-- Name: user_usergesthar_groups user_usergesthar_groups_group_id_d7c074ea_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.user_usergesthar_groups
    ADD CONSTRAINT user_usergesthar_groups_group_id_d7c074ea_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3510 (class 2606 OID 16498)
-- Name: user_usergesthar_user_permissions user_usergesthar_use_permission_id_9d17aa3b_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.user_usergesthar_user_permissions
    ADD CONSTRAINT user_usergesthar_use_permission_id_9d17aa3b_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3511 (class 2606 OID 16493)
-- Name: user_usergesthar_user_permissions user_usergesthar_use_usergesthar_id_da638d82_fk_user_user; Type: FK CONSTRAINT; Schema: public; Owner: gesthar_user
--

ALTER TABLE ONLY public.user_usergesthar_user_permissions
    ADD CONSTRAINT user_usergesthar_use_usergesthar_id_da638d82_fk_user_user FOREIGN KEY (usergesthar_id) REFERENCES public.user_usergesthar(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2026-03-23 14:31:54

--
-- PostgreSQL database dump complete
--

