# Generated by Django 4.2 on 2026-04-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(help_text='Formato: 5511999999999 (código país + DDD + número)', max_length=20, verbose_name='Número WhatsApp')),
                ('catalog_visible', models.BooleanField(default=True, verbose_name='Catálogo Visível')),
                ('company_name', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração do Catálogo',
                'verbose_name_plural': 'Configurações do Catálogo',
            },
        ),
    ]
