# Generated by Django 4.2 on 2026-04-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogconfig',
            name='instagram_url',
            field=models.CharField(blank=True, help_text='Ex: https://instagram.com/suaconta', max_length=255, null=True, verbose_name='URL Instagram'),
        ),
    ]
