# Generated by Django 4.2 on 2025-09-29 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usergesthar',
            managers=[
            ],
        ),
    ]
