# Generated by Django 4.2 on 2026-07-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usergesthar_role_useractionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractionlog',
            name='action_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EDIT', 'Edição'), ('CREATE', 'Cadastro'), ('DELETE', 'Exclusão/Inativação'), ('OTHER', 'Outro')], default='OTHER', max_length=20, verbose_name='Tipo de Ação'),
        ),
        migrations.AddField(
            model_name='useractionlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP'),
        ),
    ]
