# Generated by Django 4.2 on 2025-11-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usergesthar_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergesthar',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='usergesthar',
            name='exit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Saída'),
        ),
        migrations.AddField(
            model_name='usergesthar',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='usergesthar',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo/Função'),
        ),
    ]
