# Generated by Django 4.2 on 2026-01-07 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão')),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Fundo de Troco (Abertura)')),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de Fechamento')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Abertura')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fechamento')),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('CLOSED', 'Fechado')], default='OPEN', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Sessão de Caixa',
                'verbose_name_plural': 'Sessões de Caixa',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão')),
                ('change_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Troco')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('COMPLETED', 'Concluída'), ('CANCELED', 'Cancelada')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cash_register_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.cashregister', verbose_name='Sessão de Caixa')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='customer.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('CREDITO', 'Cartão de Crédito'), ('DEBITO', 'Cartão de Débito'), ('PIX', 'PIX'), ('OUTROS', 'Outros')], default='DINHEIRO', max_length=20, verbose_name='Método de Pagamento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Pago')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku_snapshot', models.CharField(blank=True, max_length=50)),
                ('product_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='product.productvariation')),
            ],
            options={
                'verbose_name': 'Item da Venda',
                'verbose_name_plural': 'Itens da Venda',
            },
        ),
    ]
