# Generated by Django 4.2 on 2026-05-11 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('MERCADO_PAGO', 'Mercado Pago')], db_index=True, default='MERCADO_PAGO', max_length=30, verbose_name='Gateway')),
                ('order_id', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='Order ID')),
                ('payment_id', models.CharField(blank=True, max_length=80, verbose_name='Payment ID')),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Referência Externa')),
                ('terminal_id', models.CharField(blank=True, max_length=120, verbose_name='Terminal')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor')),
                ('status', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Status')),
                ('status_detail', models.CharField(blank=True, max_length=80, verbose_name='Detalhe do Status')),
                ('created_date', models.DateTimeField(blank=True, null=True, verbose_name='Criado no Gateway')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload Completo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_payments', to='sales.sale', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Pagamento Gateway',
                'verbose_name_plural': 'Pagamentos Gateway',
                'ordering': ['-created_at'],
            },
        ),
    ]
