# Generated by Django 4.2 on 2026-03-23 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepayment',
            name='method',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('BOLETO', 'Boleto'), ('CREDITO', 'Cartão de Crédito'), ('DEBITO', 'Cartão de Débito'), ('PIX', 'PIX'), ('OUTROS', 'Outros')], default='DINHEIRO', max_length=20, verbose_name='Método de Pagamento'),
        ),
        migrations.CreateModel(
            name='SaleGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('boleto', 'Boleto'), ('pix', 'PIX')], max_length=10, verbose_name='Método')),
                ('charge_id', models.CharField(max_length=50, unique=True, verbose_name='Charge ID')),
                ('provider_payment_id', models.CharField(default='', max_length=50, verbose_name='Provider Payment ID')),
                ('barcode', models.CharField(default='', max_length=255, verbose_name='Código de Barras')),
                ('linha_digitavel', models.CharField(default='', max_length=255, verbose_name='Linha Digitável')),
                ('url_pdf', models.CharField(default='', max_length=255, verbose_name='URL do PDF')),
                ('qr_code_texto', models.CharField(default='', max_length=255, verbose_name='QR Code Texto')),
                ('qr_code_base64', models.CharField(default='', max_length=255, verbose_name='QR Code Base64')),
                ('url_qrcode', models.CharField(default='', max_length=255, verbose_name='URL QR Code')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('gerado_em', models.DateTimeField(auto_now_add=True, verbose_name='Gerado Em')),
                ('expirado_em', models.DateTimeField(blank=True, null=True, verbose_name='Expirado Em')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateways', to='sales.sale', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Gateway de Pagamento da Venda',
                'verbose_name_plural': 'Gateways de Pagamento da Venda',
                'db_table': 'sale_salegateway',
                'ordering': ['-gerado_em'],
            },
        ),
    ]
