# Generated by Django 4.2 on 2025-11-27 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_update_customer_fields'),
        ('sales', '0003_cashregister_sale_cash_register_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='customer.customer', verbose_name='Cliente'),
        ),
    ]
