# Generated by Django 4.2 on 2026-06-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_saleitem_unit_cost'),
        ('sales', '0003_gatewaypayment_fee_fields'),
    ]

    operations = [
    ]
